package com.mytian.lb;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig routeLineNodeTableDaoConfig;
    private final DaoConfig planNodeTableDaoConfig;
    private final DaoConfig configDaoConfig;
    private final DaoConfig userActionDaoConfig;
    private final DaoConfig parentDaoConfig;

    private final RouteLineNodeTableDao routeLineNodeTableDao;
    private final PlanNodeTableDao planNodeTableDao;
    private final ConfigDao configDao;
    private final UserActionDao userActionDao;
    private final ParentDao parentDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        routeLineNodeTableDaoConfig = daoConfigMap.get(RouteLineNodeTableDao.class).clone();
        routeLineNodeTableDaoConfig.initIdentityScope(type);

        planNodeTableDaoConfig = daoConfigMap.get(PlanNodeTableDao.class).clone();
        planNodeTableDaoConfig.initIdentityScope(type);

        configDaoConfig = daoConfigMap.get(ConfigDao.class).clone();
        configDaoConfig.initIdentityScope(type);

        userActionDaoConfig = daoConfigMap.get(UserActionDao.class).clone();
        userActionDaoConfig.initIdentityScope(type);

        parentDaoConfig = daoConfigMap.get(ParentDao.class).clone();
        parentDaoConfig.initIdentityScope(type);

        routeLineNodeTableDao = new RouteLineNodeTableDao(routeLineNodeTableDaoConfig, this);
        planNodeTableDao = new PlanNodeTableDao(planNodeTableDaoConfig, this);
        configDao = new ConfigDao(configDaoConfig, this);
        userActionDao = new UserActionDao(userActionDaoConfig, this);
        parentDao = new ParentDao(parentDaoConfig, this);

        registerDao(RouteLineNodeTable.class, routeLineNodeTableDao);
        registerDao(PlanNodeTable.class, planNodeTableDao);
        registerDao(Config.class, configDao);
        registerDao(UserAction.class, userActionDao);
        registerDao(Parent.class, parentDao);
    }
    
    public void clear() {
        routeLineNodeTableDaoConfig.getIdentityScope().clear();
        planNodeTableDaoConfig.getIdentityScope().clear();
        configDaoConfig.getIdentityScope().clear();
        userActionDaoConfig.getIdentityScope().clear();
        parentDaoConfig.getIdentityScope().clear();
    }

    public RouteLineNodeTableDao getRouteLineNodeTableDao() {
        return routeLineNodeTableDao;
    }

    public PlanNodeTableDao getPlanNodeTableDao() {
        return planNodeTableDao;
    }

    public ConfigDao getConfigDao() {
        return configDao;
    }

    public UserActionDao getUserActionDao() {
        return userActionDao;
    }

    public ParentDao getParentDao() {
        return parentDao;
    }
}
