package com.mytian.lb;

import java.util.List;


import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table "ROUTE_LINE_NODE_TABLE".
 */
public class RouteLineNodeTable implements java.io.Serializable {

    private Long id;
    private Integer routeLineType;

    /**
     * Used to resolve relations
     */
    private transient DaoSession daoSession;

    /**
     * Used for active entity operations.
     */
    private transient RouteLineNodeTableDao myDao;

    private List<PlanNodeTable> planNodes;

    public RouteLineNodeTable() {
    }

    public RouteLineNodeTable(Long id) {
        this.id = id;
    }

    public RouteLineNodeTable(Long id, Integer routeLineType) {
        this.id = id;
        this.routeLineType = routeLineType;
    }

    /**
     * called by internal mechanisms, do not call yourself.
     */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getRouteLineNodeTableDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getRouteLineType() {
        return routeLineType;
    }

    public void setRouteLineType(Integer routeLineType) {
        this.routeLineType = routeLineType;
    }

    /**
     * To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity.
     */
    public List<PlanNodeTable> getPlanNodes() {
        if (planNodes == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            PlanNodeTableDao targetDao = daoSession.getPlanNodeTableDao();
            List<PlanNodeTable> planNodesNew = targetDao._queryRouteLineNodeTable_PlanNodes(id);
            synchronized (this) {
                if (planNodes == null) {
                    planNodes = planNodesNew;
                }
            }
        }
        return planNodes;
    }

    /**
     * Resets a to-many relationship, making the next get call to query for a fresh result.
     */
    public synchronized void resetPlanNodes() {
        planNodes = null;
    }

    /**
     * Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context.
     */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.delete(this);
    }

    /**
     * Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context.
     */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.update(this);
    }

    /**
     * Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context.
     */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.refresh(this);
    }

}
